export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const FETCH_USERS_TASKS_START = "FETCH_USERS_TASKS_START";
export const FETCH_USERS_TASKS_SUCCESS = "FETCH_USERS_TASKS_SUCCESS";
export const FETCH_USERS_TASKS_ERROR = "FETCH_USERS_TASKS_ERROR";